FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY muavangbac_bot.py .

ENV TELEGRAM_BOT_TOKEN=""
ENV TELEGRAM_CHAT_ID=""
ENV TIMEZONE=""

EXPOSE 8082

CMD ["python", "muavangbac_bot.py"]
